In [144]:
import numpy as np
import pandas as pd
import re
import math
from pyproj import Proj
import datetime


emergencies = pd.read_csv('../datasets/emergencies.csv', sep=';')
averias = pd.read_csv('../datasets/averias.csv', sep=';')
reclamaciones = pd.read_csv('../datasets/reclamaciones.csv', sep= ';')
averias_bcn = pd.read_csv("../datasets/averias_dis.csv", sep=",")

/Users/ireneroma/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [174]:
accidentes.head(10)

          dist   any  mes  dia  hora      Long        Lat
0  Sant Mart�_  2016    4    5    10  2.186566  41.412487
1  Sant Mart�_  2016    2   13    14  2.186565  41.412595
2  Sant Mart�_  2016   12   15     8  2.183345  41.416527
3  Sant Mart�_  2016    5   20    13  2.184785  41.416204
4  Sant Mart�_  2016    5   31     0  2.177437  41.413377
5  Sant Mart�_  2016   12   24     5  2.180602  41.414823
6  Sant Mart�_  2016    6   14     9  2.180391  41.415434
7  Sant Mart�_  2016   12   17    10  2.177640  41.410550
8  Sant Mart�_  2016    5    8    17  2.178164  41.410806
9  Sant Mart�_  2016   11   11    16  2.180769  41.412924

In [45]:
bomberos = consumos[consumos.tipo=='SERVEI EQUIP C.INCENDIS']
beixample = bomberos[bomberos.dis=='EIXAMPLE']
beixample.ano = pd.to_numeric(beixample.ano)
comercial = beixample[beixample.uso=='INDUSTRIAL']

In [48]:
comercial.sort(['ano','mun','dis','uso','tipo','consumo','contratos'], ascending=[True, False, False, False, False, False, False]).head()

/Users/ireneroma/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

,ano,mun,dis,uso,tipo,consumo,contratos
8627,201103,BARCELONA,CIUTAT VELLA,INDUSTRIAL,SERVEI EQUIP C.INCENDIS,0,105.0
10306,201105,BARCELONA,CIUTAT VELLA,INDUSTRIAL,SERVEI EQUIP C.INCENDIS,0,1.0
8694,201201,BARCELONA,CIUTAT VELLA,INDUSTRIAL,SERVEI EQUIP C.INCENDIS,0,3.0
10379,201203,BARCELONA,CIUTAT VELLA,INDUSTRIAL,SERVEI EQUIP C.INCENDIS,0,107.0
10639,201211,BARCELONA,CIUTAT VELLA,INDUSTRIAL,SERVEI EQUIP C.INCENDIS,0,1.0

In [175]:
aeixample = accidentes[accidentes.dist=="Eixample"]
aeixample["date"] = aeixample["dia"].map(str) + str("-") + aeixample["mes"].map(str) + str("-") + aeixample["any"].map(str)

/Users/ireneroma/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [176]:
aeixample

           dist   any  mes  dia  hora      Long        Lat        date
217    Eixample  2016    7   11    16  2.153138  41.376306   11-7-2016
218    Eixample  2016    1   24     0  2.154036  41.377160   24-1-2016
220    Eixample  2016   12   13    11  2.154809  41.376580  13-12-2016
221    Eixample  2016    7   27    14  2.154507  41.376803   27-7-2016
222    Eixample  2016    6   16    18  2.154507  41.376803   16-6-2016
223    Eixample  2016    3    8    16  2.154507  41.376803    8-3-2016
228    Eixample  2016    4    9    12  2.153798  41.375194    9-4-2016
229    Eixample  2016    1   27    10  2.152818  41.375196   27-1-2016
230    Eixample  2016    8   24    21  2.152733  41.376177   24-8-2016
231    Eixample  2016   10    7    19  2.146197  41.386767   7-10-2016
232    Eixample  2016    7    6    20  2.164968  41.375159    6-7-2016
233    Eixample  2016    8    3    17  2.162815  41.375170    3-8-2016
234    Eixample  2016    5    5    13  2.158521  41.381768    5-5-2016
235    Eixample  2016    5    4    16  2.159038  41.381574    4-5-2016
236    Eixample  2016   12   30    15  2.158784  41.381761  30-12-2016
237    Eixample  2016    9   14    12  2.146182  41.387911   14-9-2016
238    Eixample  2016    5    2    10  2.161113  41.375509    2-5-2016
239    Eixample  2016    3   26     1  2.146847  41.385538   26-3-2016
240    Eixample  2016    7   15    20  2.147933  41.386600   15-7-2016
241    Eixample  2016    3   18     9  2.147933  41.386600   18-3-2016
242    Eixample  2016    1   14    13  2.160161  41.380726   14-1-2016
243    Eixample  2016    4   24    22  2.158255  41.377380   24-4-2016
244    Eixample  2016    3   31    12  2.159984  41.381446   31-3-2016
245    Eixample  2016    6    3    16  2.159984  41.381446    3-6-2016
246    Eixample  2016    3    9    16  2.144992  41.389262    9-3-2016
247    Eixample  2016   11   11    13  2.160631  41.378577  11-11-2016
248    Eixample  2016    7    4    14  2.159709  41.381462    4-7-2016
249    Eixample  2016    7   23    12  2.159648  41.381515   23-7-2016
250    Eixample  2016    8   31    17  2.162008  41.383118   31-8-2016
251    Eixample  2016    9   23    11  2.161573  41.383412   23-9-2016
...         ...   ...  ...  ...   ...       ...        ...         ...
9972   Eixample  2016   10   26    11  2.179978  41.399740  26-10-2016
9973   Eixample  2016    9   15     8  2.178687  41.397776   15-9-2016
9974   Eixample  2016    3   11    17  2.181079  41.398712   11-3-2016
9976   Eixample  2016    1   28     3  2.178476  41.397414   28-1-2016
9977   Eixample  2016    5   23    14  2.178476  41.397414   23-5-2016
9978   Eixample  2016   12    1    12  2.178510  41.397577   1-12-2016
9979   Eixample  2016    6   15    17  2.178510  41.397577   15-6-2016
9980   Eixample  2016   10   31    13  2.178510  41.397577  31-10-2016
9981   Eixample  2016    6    3    18  2.180199  41.394544    3-6-2016
9982   Eixample  2016    7   29    16  2.182265  41.399594   29-7-2016
9983   Eixample  2016    5    7    12  2.181768  41.399122    7-5-2016
9984   Eixample  2016    7   18    11  2.183757  41.398875   18-7-2016
9985   Eixample  2016    7   19    10  2.185148  41.396651   19-7-2016
9986   Eixample  2016    9   28    18  2.174625  41.399206   28-9-2016
9987   Eixample  2016    6   22    13  2.174625  41.399206   22-6-2016
9988   Eixample  2016   11   21    15  2.174695  41.399351  21-11-2016
9989   Eixample  2016    8   28     0  2.175494  41.398609   28-8-2016
9990   Eixample  2016    6   22    17  2.176205  41.399119   22-6-2016
9991   Eixample  2016    4    8    11  2.174936  41.400145    8-4-2016
9992   Eixample  2016   11    8    18  2.173828  41.399840   8-11-2016
9993   Eixample  2016    3   12     0  2.183447  41.395883   12-3-2016
9994   Eixample  2016    5   21    11  2.186639  41.396040   21-5-2016
9995   Eixample  2016    4    9    16  2.185644  41.401032    9-4-2016
9996   Eixample  2016    5   19    17  2.176224  41.400470   19-5-2016
9997   Eixample  2016   11   11     8  2.175412  41.400365  11-11-2016
9998   Eixample  2016   11    9    15  2.186696  41.398238   9-11-2016
9999   Eixample  2016   12   16    12  2.178749  41.399452  16-12-2016
10000  Eixample  2016    6   14    11  2.177987  41.400140   14-6-2016
10001  Eixample  2016    8   13    17  2.177987  41.400140   13-8-2016
10002  Eixample  2016    9   12    18  2.184182  41.400283   12-9-2016

[3280 rows x 8 columns]