In [125]:
import numpy as np
import pandas as pd
import re
import math

consumos = pd.read_csv('../datasets/consumos.csv',sep=';')
tuberia = pd.read_csv('../datasets/tuberia.csv',sep=';')
slice1 = pd.read_csv('../datasets/slice1.csv', sep=";")
slice2 = pd.read_csv('../datasets/slice2.csv', sep=";")

### Consumos

### Presencia

### Tuber√≠a

In [14]:
consumos.columns = ['ano','mun','dis','uso','tipo','consumo','contratos']

In [15]:
consumos.tipo.unique()

array(['SUBMINISTRAMENT AFORAMENT GENERAL',
       'SUBMINISTRAMENT COMPTADOR DIVISIONARI', 'SERVEI EQUIP C.INCENDIS',
       'SUBMINISTRAMENT COMPTADOR GENERAL',
       'SUBMINISTRAMENT AFORAMENT DIVISIONARI'], dtype=object)

In [16]:
consumos[(consumos.mun=='BADALONA') & (consumos.tipo=='SUBMINISTRAMENT AFORAMENT GENERAL') & (consumos.uso=='INDUSTRIAL')]

,ano,mun,dis,uso,tipo,consumo,contratos
8322,201110,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,8556,16.0
8324,201201,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,8462,16.0
8329,201204,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,8462,16.0
8336,201210,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,8832,16.0
8341,201301,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,5663,16.0
8346,201307,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,6428,17.0
8352,201401,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,5745,17.0
8357,201406,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,152,1.0
8361,201409,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,5208,16.0
8370,201505,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,5507,17.0
8375,201601,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,4972,16.0
8380,201605,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,5141,16.0
8383,201607,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,5225,16.0
8387,201611,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,5225,16.0
9782,201101,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,8280,16.0
9784,201104,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,8371,16.0
9787,201107,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,8464,16.0
10007,201309,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,5844,17.0
10011,201403,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,5940,17.0
10013,201405,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,5452,17.0
10015,201407,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,5690,16.0
10018,201411,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,5806,16.0
10022,201503,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,4783,17.0
10024,201504,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,724,1.0
10028,201507,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,5721,17.0
10035,201510,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,80,1.0
10036,201511,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,6489,16.0
10040,201603,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,5225,16.0
10045,201609,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,5058,16.0
10047,201612,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,-1294,2.0
13571,201205,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,-92,1.0
13573,201207,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,8832,16.0
13580,201303,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,5855,16.0
13583,201305,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,5611,17.0
13587,201311,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,6038,17.0
13597,201501,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,5296,16.0
13805,201509,BADALONA,Sense Informar,INDUSTRIAL,SUBMINISTRAMENT AFORAMENT GENERAL,3793,16.0

In [151]:
consumos[consumos.tipo=='SERVEI EQUIP C.INCENDIS'].head()

AttributeError: 'DataFrame' object has no attribute 'tipo'

In [91]:
presencia = pd.read_csv('muestra.csv',sep=';')

In [92]:
presencia.head()

    X ETRS89    Y ETRS89   data_prev
0  432036.69  4586539.86  2018-09-30
1  432036.69  4586539.86  2021-09-29
2  431835.51  4586562.26  2020-09-29
3  431835.51  4586562.26  2019-09-30
4  431835.51  4586562.26  2022-09-29

In [94]:
presencia.columns = ['x1','y1','data']

In [95]:
from pyproj import Proj

In [108]:
myProj = Proj("+proj=utm +zone=31K, +north +ellps=WGS84 +datum=WGS84 +units=m +no_defs")

In [109]:
lon, lat = myProj(presencia['x1'].values, presencia['y1'].values, inverse=True)

In [110]:
lon,lat

(array([ 2.18661444,  2.18661444,  2.18420443, ...,  2.11357208,
         2.11493329,  2.11493329]),
 array([ 41.42754743,  41.42754743,  41.42773213, ...,  41.39414014,
         41.39306702,  41.39306702]))

In [111]:
C

In [112]:
coord.head()

        Lon        Lat
0  2.186614  41.427547
1  2.186614  41.427547
2  2.184204  41.427732
3  2.184204  41.427732
4  2.184204  41.427732

In [113]:
coord['data'] = presencia['data']

In [114]:
coord.head()

        Lon        Lat        data
0  2.186614  41.427547  2018-09-30
1  2.186614  41.427547  2021-09-29
2  2.184204  41.427732  2020-09-29
3  2.184204  41.427732  2019-09-30
4  2.184204  41.427732  2022-09-29

In [115]:
coord.to_csv('coord.csv',sep=';')

In [132]:
presencia_bcn = pd.read_csv('../datasets/presencia_bcn.csv',sep=';')

In [133]:
presencia_bcn.head()

,lon,lat,data,source_n_distri,source_c_distri,Unnamed: 5
0,2.132828,41.405077,30/5/22,SARRIA - SANT GERVASI,5,NaN
1,2.132828,41.405077,30/5/20,SARRIA - SANT GERVASI,5,NaN
2,2.132828,41.405077,31/5/19,SARRIA - SANT GERVASI,5,NaN
3,2.132828,41.405077,31/5/18,SARRIA - SANT GERVASI,5,NaN
4,2.128592,41.397833,30/4/19,SARRIA - SANT GERVASI,5,NaN

In [20]:
tuberia.columns = ['mun','puesta','dis','dificultat','xarxa','diametre','longitud']

In [21]:
tuberia.dificultat.unique()

array(['Baixa', 'Normal', 'Alta'], dtype=object)

In [22]:
tuberia.diametre.unique()

array(['160,000 mm', '110,000 mm', '100,000 mm', '150,000 mm',
       '300,000 mm', '225,000 mm', '200,000 mm', '50,000 mm', '32,000 mm',
       '63,000 mm', '40,000 mm', '80,000 mm', '60,000 mm', '600,000 mm',
       '400,000 mm', '500,000 mm', '75,000 mm', '800,000 mm', '25,000 mm',
       '355,000 mm', '250,000 mm', '125,000 mm', '20,000 mm', '90,000 mm',
       '560,000 mm', '1.200,000 mm', '700,000 mm', '65,000 mm',
       '1.250,000 mm', '1.100,000 mm', '630,000 mm', '315,000 mm',
       '1.000,000 mm', '900,000 mm', '350,000 mm', '30,000 mm',
       '1.400,000 mm', '1.600,000 mm', '1.500,000 mm'], dtype=object)

In [23]:
tuberia[(tuberia.dificultat == "Baixa")]

,mun,puesta,dis,dificultat,xarxa,diametre,longitud
0,Sant Climent de Llobregat,2015-03-04,NaN,Baixa,Distribuci√≥,"160,000 mm","23,500 m"
1,Sant Climent de Llobregat,2015-10-16,NaN,Baixa,Distribuci√≥,"110,000 mm","101,060 m"
5,Barcelona,2010-07-20,Horta - Guinard√≥,Baixa,Distribuci√≥,"300,000 mm","2,180 m"
6,Barcelona,2010-07-15,Horta - Guinard√≥,Baixa,Distribuci√≥,"225,000 mm","26,750 m"
7,Barcelona,2010-10-25,Horta - Guinard√≥,Baixa,Distribuci√≥,"300,000 mm","45,660 m"
8,Barcelona,2011-05-27,Horta - Guinard√≥,Baixa,Distribuci√≥,"225,000 mm","36,780 m"
9,Barcelona,2011-08-02,Horta - Guinard√≥,Baixa,Distribuci√≥,"225,000 mm","3,590 m"
10,Barcelona,2011-04-13,Horta - Guinard√≥,Baixa,Distribuci√≥,"200,000 mm","0,810 m"
11,Barcelona,2011-07-27,Horta - Guinard√≥,Baixa,Distribuci√≥,"200,000 mm","243,870 m"
12,Barcelona,2011-07-28,Horta - Guinard√≥,Baixa,Distribuci√≥,"150,000 mm","1,690 m"
14,Barcelona,2013-02-28,Sarri√† - Sant Gervasi,Baixa,Distribuci√≥,"150,000 mm","22,290 m"
17,Barcelona,2013-03-26,Horta - Guinard√≥,Baixa,Distribuci√≥,"100,000 mm","55,950 m"
20,Barcelona,2013-11-22,Horta - Guinard√≥,Baixa,Distribuci√≥,"225,000 mm","207,480 m"
21,Barcelona,2013-12-05,Horta - Guinard√≥,Baixa,Distribuci√≥,"200,000 mm","0,810 m"
22,Barcelona,2013-12-05,Horta - Guinard√≥,Baixa,Distribuci√≥,"225,000 mm","3,940 m"
23,Barcelona,2013-12-05,Horta - Guinard√≥,Baixa,Distribuci√≥,"150,000 mm","1,840 m"
29,Barcelona,2016-04-14,Horta - Guinard√≥,Baixa,Distribuci√≥,"110,000 mm","55,810 m"
30,Barcelona,2016-07-05,Horta - Guinard√≥,Baixa,Distribuci√≥,"100,000 mm","65,430 m"
32,Barcelona,2012-04-19,Horta - Guinard√≥,Baixa,Distribuci√≥,"110,000 mm","133,890 m"
33,Barcelona,2012-12-12,Horta - Guinard√≥,Baixa,Distribuci√≥,"32,000 mm","1,860 m"
34,Barcelona,2013-02-21,Horta - Guinard√≥,Baixa,Distribuci√≥,"50,000 mm","95,820 m"
35,Castelldefels,2010-02-12,NaN,Baixa,Distribuci√≥,"110,000 mm","34,710 m"
36,Castelldefels,2010-02-25,NaN,Baixa,Distribuci√≥,"110,000 mm","11,240 m"
37,Castelldefels,2010-10-20,NaN,Baixa,Distribuci√≥,"100,000 mm","58,980 m"
38,Castelldefels,2012-10-18,NaN,Baixa,Distribuci√≥,"110,000 mm","9,050 m"
40,Castelldefels,2015-04-14,NaN,Baixa,Distribuci√≥,"160,000 mm","52,250 m"
41,Castelldefels,2015-04-14,NaN,Baixa,Distribuci√≥,"200,000 mm","11,020 m"
42,Castelldefels,2015-04-14,NaN,Baixa,Distribuci√≥,"160,000 mm","16,310 m"
43,Castelldefels,2016-01-29,NaN,Baixa,Distribuci√≥,"110,000 mm","20,580 m"
44,Castelldefels,2016-01-29,NaN,Baixa,Distribuci√≥,"110,000 mm","128,080 m"
...,...,...,...,...,...,...,...
13800,Badalona,2010-06-17,NaN,Baixa,Distribuci√≥,"100,000 mm","13,670 m"
13801,Badalona,2010-06-17,NaN,Baixa,Distribuci√≥,"100,000 mm","33,280 m"
13802,Badalona,2010-06-07,NaN,Baixa,Distribuci√≥,"200,000 mm","4,960 m"
13803,Badalona,2013-01-16,NaN,Baixa,Distribuci√≥,"100,000 mm","14,340 m"
13804,Badalona,2013-05-23,NaN,Baixa,Distribuci√≥,"150,000 mm","18,090 m"
13805,Badalona,2016-02-29,NaN,Baixa,Distribuci√≥,"50,000 mm","18,160 m"
13806,Badalona,2016-11-28,NaN,Baixa,Distribuci√≥,"32,000 mm","3,010 m"
13808,Barcelona,2011-04-20,Nou Barris,Baixa,Distribuci√≥,"100,000 mm","0,800 m"
13810,Barcelona,2013-01-18,Nou Barris,Baixa,Distribuci√≥,"200,000 mm","105,700 m"
13811,Barcelona,2013-04-09,Nou Barris,Baixa,Distribuci√≥,"150,000 mm","1,020 m"
13812,Barcelona,2013-04-09,Nou Barris,Baixa,Distribuci√≥,"150,000 mm","0,720 m"
13813,Barcelona,2013-12-11,Nou Barris,Baixa,Distribuci√≥,"160,000 mm","203,520 m"
13814,Barcelona,2013-12-11,Nou Barris,Baixa,Distribuci√≥,"75,000 mm","1,310 m"
13815,Barcelona,2013-12-11,Nou Barris,Baixa,Distribuci√≥,"75,000 mm","1,030 m"
13816,Barcelona,2013-12-20,Nou Barris,Baixa,Distribuci√≥,"160,000 mm","66,350 m"
13817,Barcelona,2013-12-20,Nou Barris,Baixa,Distribuci√≥,"75,000 mm","23,140 m"
13818,Barcelona,2013-12-20,Nou Barris,Baixa,Distribuci√≥,"75,000 mm","17,840 m"
13819,Barcelona,2014-03-21,Nou Barris,Baixa,Distribuci√≥,"75,000 mm","6,290 m"
13820,Barcelona,2014-03-21,Nou Barris,Baixa,Distribuci√≥,"75,000 mm","24,140 m"
13821,Barcelona,2014-03-21,Nou Barris,Baixa,Distribuci√≥,"75,000 mm","18,700 m"
13822,Barcelona,2014-03-21,Nou Barris,Baixa,Distribuci√≥,"75,000 mm","1,200 m"
13823,Barcelona,2014-03-21,Nou Barris,Baixa,Distribuci√≥,"75,000 mm","20,270 m"
13824,Barcelona,2014-03-21,Nou Barris,Baixa,Distribuci√≥,"75,000 mm","23,710 m"
13825,Barcelona,2014-03-21,Nou Barris,Baixa,Distribuci√≥,"75,000 mm","17,770 m"
13826,Barcelona,2014-05-20,Nou Barris,Baixa,Distribuci√≥,"160,000 mm","6,630 m"
13827,Barcelona,2014-07-04,Nou Barris,Baixa,Distribuci√≥,"32,000 mm","3,990 m"
13828,Barcelona,2014-09-17,Nou Barris,Baixa,Distribuci√≥,"160,000 mm","48,700 m"
13832,Barcelona,2013-01-18,Nou Barris,Baixa,Distribuci√≥,"160,000 mm","18,770 m"
13833,Barcelona,2014-10-09,Nou Barris,Baixa,Distribuci√≥,"160,000 mm","1,100 m"
13835,Barcelona,2014-12-17,Nou Barris,Baixa,Distribuci√≥,"110,000 mm","46,980 m"

In [46]:
import matplotlib.pylab as plt
from datetime import datetime
%matplotlib inline
from matplotlib.pylab import rcParams
rcParams['figure.figsize'] = 15, 6

In [13]:
slice1.head()

,DESC_MUNI,DES_DISTRIC,ANYMES_CAL,DESC_TIP_SUBM,CONSUM,USO,ContratoCOD
0,BEGUES,Sense Informar,201406,SUBMINISTRAMENT COMPTADOR GENERAL,33,DOMESTIC,C481816721
1,BEGUES,Sense Informar,201602,SUBMINISTRAMENT COMPTADOR GENERAL,25,DOMESTIC,C481816721
2,BEGUES,Sense Informar,201610,SUBMINISTRAMENT COMPTADOR GENERAL,39,DOMESTIC,C481816721
3,BEGUES,Sense Informar,201510,SUBMINISTRAMENT COMPTADOR GENERAL,37,DOMESTIC,C481816721
4,BEGUES,Sense Informar,201112,SUBMINISTRAMENT COMPTADOR GENERAL,50,DOMESTIC,C481816721

In [14]:
print slice1.dtypes

DESC_MUNI        object
DES_DISTRIC      object
ANYMES_CAL        int64
DESC_TIP_SUBM    object
CONSUM            int64
USO              object
ContratoCOD      object
dtype: object

In [152]:
slice1.ANYMES_CAL = pd.to_datetime(slice1.ANYMES_CAL, format = '%Y%m')

In [131]:
slice2.DES_DISTRIC.unique()

array(['SARRIA - SANT GERVASI', 'NOU BARRIS', 'CIUTAT VELLA', 'EIXAMPLE',
       'SANT MARTI', 'SANTS-MONTJUIC', 'SANT ANDREU', 'HORTA - GUINARDO',
       'GRACIA', 'LES CORTS', 'Sense Informar'], dtype=object)

In [136]:
presencia_bcn.source_n_distri.unique()

array(['SARRIA - SANT GERVASI', 'HORTA - GUINARDO', 'CIUTAT VELLA',
       'EIXAMPLE', 'SANTS-MONTJUIC', 'LES CORTS', 'GRACIA', 'NOU BARRIS',
       'SANT ANDREU', 'SANT MARTI'], dtype=object)

In [137]:
slice2[slice2.DES_DISTRIC == "GRACIA"].head()

,DESC_MUNI,DES_DISTRIC,ANYMES_CAL,DESC_TIP_SUBM,CONSUM,USO,ContratoCOD
1162,BARCELONA,GRACIA,201303,SUBMINISTRAMENT COMPTADOR DIVISIONARI,3,COMERCIAL,C401285416
1163,BARCELONA,GRACIA,201201,SUBMINISTRAMENT COMPTADOR DIVISIONARI,3,COMERCIAL,C401285416
1164,BARCELONA,GRACIA,201104,SUBMINISTRAMENT COMPTADOR DIVISIONARI,3,COMERCIAL,C401285416
1165,BARCELONA,GRACIA,201306,SUBMINISTRAMENT COMPTADOR DIVISIONARI,2,COMERCIAL,C401285416
1166,BARCELONA,GRACIA,201305,SUBMINISTRAMENT COMPTADOR DIVISIONARI,2,COMERCIAL,C401285416

In [149]:
user = slice2[slice2.ContratoCOD=='C357424167']
distrito = user.DES_DISTRIC
revision = presencia_bcn[presencia_bcn.source_n_distri == ]

2453    GRACIA
2454    GRACIA
2455    GRACIA
2456    GRACIA
2457    GRACIA
2458    GRACIA
2459    GRACIA
2460    GRACIA
2461    GRACIA
2462    GRACIA
2463    GRACIA
2464    GRACIA
2465    GRACIA
2466    GRACIA
2467    GRACIA
2468    GRACIA
2469    GRACIA
2470    GRACIA
2471    GRACIA
2472    GRACIA
2473    GRACIA
2474    GRACIA
2475    GRACIA
2476    GRACIA
2477    GRACIA
2478    GRACIA
2479    GRACIA
2480    GRACIA
2481    GRACIA
2482    GRACIA
2483    GRACIA
2484    GRACIA
Name: DES_DISTRIC, dtype: object

In [147]:
type(distrito)

str

In [150]:
revision.head()

,lon,lat,data,source_n_distri,source_c_distri,Unnamed: 5
19117,2.167748,41.404097,30/4/17,GRACIA,6,NaN
19118,2.167748,41.404097,29/4/21,GRACIA,6,NaN
19119,2.167826,41.402830,29/4/22,GRACIA,6,NaN
19120,2.167826,41.402830,30/4/18,GRACIA,6,NaN
19121,2.162752,41.400786,30/4/17,GRACIA,6,NaN